#!/bin/bash
find_offenders() {
    # .bin is stripped because Mac App Store has problems with symlinks there
    find . \
            -name example          \
        -or -name examples         \
        -or -name test             \
        -or -name tests            \
        -or -name testsuite        \
        -or -name spec             \
        -or -name docs             \
        -or -name tmp              \
        -or -name .idea            \
        -or -name dist             \
        -or -name cache            \
        -or -name .bin             \
        -or -name 'fsevent_watch*' \
        -or -name '*.o'            \
        -or -name '*.h'            \
        -or -name '*.c'            \
        -or -name 'ffc_i'          \
        -or -path '*/ext/json/*'   \

}
find_offenders
find_offenders | xargs rm -rf
