#! /bin/bash

stage_and_commit() {
    echo Committing $1...
    git add -A .
    git commit -m "Update $1" && git log -1
}

prev=$(pwd)
compiler=$1
echo Updating $compiler...
cd $compiler.lrplugin
rm -rf node_modules
while test -n "$2"; do
    echo "npm install $2"
    npm install $2
    shift
done
cd node_modules
stage_and_commit $compiler
cd $prev
