#! /bin/bash

./update-npm  CoffeeScript   coffee-script
./update-npm  IcedCoffeeScript iced-coffee-script
./update-npm  Eco            eco
./update-npm  LESS           less
./update-npm  Stylus         stylus
./update-npm  Jade           jade markdown

./update-gem  SASS  sass compass chunky_png
./update-gem  SLIM  slim temple tilt
./update-gem  HAML  haml
