# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{compass-squaregrid-plugin}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Rice"]
  s.date = %q{2011-01-17}
  s.description = %q{The Square Grid System is a simple grid system for designers and developers http://thesquaregrid.com/}
  s.email = %q{me@davidjrice.co.uk}
  s.extra_rdoc_files = [
    "README.mkdn"
  ]
  s.files = [
    ".gitignore",
     "README.mkdn",
     "Rakefile",
     "VERSION",
     "compass-squaregrid-plugin.gemspec",
     "lib/squaregrid.rb",
     "stylesheets/squaregrid/_grid.sass",
     "stylesheets/squaregrid/_text.sass",
     "templates/project/grid.sass",
     "templates/project/manifest.rb",
     "templates/project/text.sass"
  ]
  s.homepage = %q{http://github.com/davidjrice/compass-squaregrid-plugin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{The Square Grid System is a simple grid system for designers and developers http://thesquaregrid.com/}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<compass>, [">= 0.10.0"])
    else
      s.add_dependency(%q<compass>, [">= 0.10.0"])
    end
  else
    s.add_dependency(%q<compass>, [">= 0.10.0"])
  end
end

