/*
		Compiles single livescript file
		It assumes 3 arguments: pathToLiveScriptDir [arguments] sourceFileWithPath, destinationFileWithPath
 */



var fs = require("fs");
var path = require("path");


if (process.argv.length < 5) {
	process.stderr.write("Usage: node compile-file pathToLiveScriptDir [arguments] sourceFileWithPath, destinationFileWithPath");
	return;
}


var lsPath = process.argv[2];
var destination = process.argv[process.argv.length-1];

var outputData = "";

process.argv[1] = path.resolve(path.join(lsPath, "lib", "command"));
process.argv.splice(2, 1);
process.argv.splice(process.argv.length-1, 1);

var stdoutWrite = process.stdout.write;
process.stdout.write = function(data) {
	outputData += data;
	stdoutWrite.apply(this, arguments);
}

require(process.argv[1]);

process.on('exit', function (){
	if (outputData.length > 0) {
		var version = require(lsPath + "/lib/livescript").VERSION
		fs.writeFileSync(destination, "// Generated by LiveScript " + version + "\n" + outputData);
	}
});
