// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var key, val, _ref;



  _ref = require('./coffee-script');
  for (key in _ref) {
    val = _ref[key];
    exports[key] = val;
  }

}).call(this);
